name: OSV-Scanner with SBOM

on:
  schedule:
    - cron: "40 10 * * *"
  push:
    branches: [main]

permissions:
  actions: read
  security-events: write
  contents: read

jobs:
  osv-scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # Install OSV-Scanner (official method)
    - name: Install OSV-Scanner
      uses: google/osv-scanner/actions/setup@v1
      with:
        version: v2.0.0

    # Install build tools and SBOM generator
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake
        curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin

    - name: Configure project
      run: cmake -B build -DCMAKE_EXPORT_COMPILE_COMMANDS=ON .

    - name: Build project
      run: cmake --build build
  
    # Generate SBOM using Syft
    - name: Generate SBOM
      run: |
        syft packages dir:. --output cyclonedx-json --file sbom.json

    # Run OSV-Scanner on SBOM
    - name: Scan dependencies
      run: |
        osv-scanner --sbom=sbom.json --format=json --output=results.json

    # Upload results (using v4 which is current latest)
    - name: Upload scan results
      uses: actions/upload-artifact@v4
      with:
        name: vulnerability-scan-results
        path: results.json

    # Upload to GitHub security tab
    - name: Upload SARIF results
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: results.json
