name: OSV-Scanner with SBOM

on:
  schedule:
    - cron: "2 * * * *"
  push:
    branches: [main]

permissions:
  actions: read
  security-events: write
  contents: read

jobs:
  osv-scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # Install OSV-Scanner (correct method)
    - name: Install OSV-Scanner
      run: |
        apk add osv-scanner
        osv-scanner --version

    # Install build tools and Syft
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake
        curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin

    # Generate SBOM
    - name: Generate SBOM
      run: |
        syft packages dir:. --output cyclonedx-json --file sbom.json

    # Run vulnerability scan
    - name: Scan dependencies
      run: |
        osv-scanner --sbom=sbom.json --format=json --output=results.json

    # Upload results
    - name: Upload scan results
      uses: actions/upload-artifact@v4
      with:
        name: vulnerability-scan-results
        path: results.json

    # Upload to security tab
    - name: Upload SARIF results
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: results.json
