name: OSV-Scanner with SBOM

on:
  schedule:
    - cron: "33 10 * * *"
  push:
    branches: [main]

permissions:
  actions: read
  security-events: write
  contents: read

jobs:
  osv-scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # Install OSV-Scanner (official method)
    - name: Install OSV-Scanner
      uses: google/osv-scanner/actions/setup@v1
      with:
        version: v2.0.0

    # Install build tools for C++
    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake

    - name: Configure project
      run: cmake -B build -DCMAKE_EXPORT_COMPILE_COMMANDS=ON .

    - name: Build project
      run: cmake --build build
    # Generate SBOM using Syft
    - name: Generate SBOM
      uses: anchore/sbom-action@v0
      with:
        output-format: cyclonedx-json
        output-file: sbom.json

    # Run OSV-Scanner on SBOM
    - name: Scan dependencies
      run: |
        osv-scanner --sbom=sbom.json --format=json --output=results.json

    # Upload results
    - name: Upload scan results
      uses: actions/upload-artifact@v3
      with:
        name: vulnerability-scan-results
        path: results.json

    # Optional: Upload to GitHub security tab
    - name: Upload SARIF results
      if: always()
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: results.json
